export const ADD_TO_CART="ADD_TO_CART";
export const REMOVE_FROM_CART="REMOVE_FROM_CART"

export const FOOD_DATA_LOADING="FOOD_DATA_LOADING";
export const FOOD_DATA_SUCCESS="FOOD_DATA_SUCCESS";
export const FOOD_DATA__FAILURE="FOOD_DATA_FAIL"
export const FOOD_DATA_BY_CATEGORY="FOOD_DATA_BY_CATEGORY"

export const REGISTER_USER_LOADING="REGISTER_USER_LOADING";
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILS="REGISTER_USER_FAILS";

export const LOGIN_USER_LOADING="LOGIN_USER_LOADING";
export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILS="LOGIN_USER_FAILS";

export const LOGOUT_USER="LOGOUT_USER";